name: Fetch Exchange Rates

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4